// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ListComposes():Promise<Array<domain.DcViewerCompose>>;

export function ReadComposeFile(arg1:string):Promise<domain.Compose>;

export function UploadCompose():Promise<domain.DcViewerCompose>;
