// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ReadComposeFile(arg1:string):Promise<domain.Compose>;

export function UploadCompose():Promise<void>;
