// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListComposes() {
  return window['go']['main']['App']['ListComposes']();
}

export function ReadComposeFile(arg1, arg2) {
  return window['go']['main']['App']['ReadComposeFile'](arg1, arg2);
}

export function UploadCompose() {
  return window['go']['main']['App']['UploadCompose']();
}
